#!/bin/bash

DIR="$(readlink -f $(dirname $0))"
UID_GID=`id -u`:`id -g`
DOCKER_IMG="zultron/freeipa-cloud-prov:latest"
DO_API_KEY=$(awk '/^token:/ {print $2}' config.yaml)


cd "$DIR"

if tty >/dev/null; then
    DOCKER_TTY_ARGS="-t"
fi

if test "$1" = "-b"; then
    set -x
    exec docker build -t ${DOCKER_IMG} .

elif test "${1:0:1}" = "-"; then
    {
	echo "Usage:"
	echo "    $0 -b              # build container"
	echo "    $0 COMMAND ARG ... # run command with args in container"
    } >&2
    exit 1

else
    shift
    set -x
    exec docker run --rm -i ${DOCKER_TTY_ARGS} \
	-v $HOME:/home/user \
	-v $PWD:/data \
	-u $UID_GID \
	--entrypoint /bin/bash \
	-e DO_API_KEY=${DO_API_KEY} \
	${DOCKER_IMG} "$@"
fi
