#!/bin/bash

DIR="$(readlink -f $(dirname $0))"
UID_GID=`id -u`:`id -g`
DOCKER_IMG="zultron/freeipa-cloud-prov:master"

cd "$DIR"

if tty >/dev/null; then
    DOCKER_TTY_ARGS="-t"
fi

if test "$1" = "build"; then
    set -x
    docker build -t ${DOCKER_IMG} .

elif test "$1" = "shell"; then
    shift
    set -x
    docker run --rm -i ${DOCKER_TTY_ARGS} \
	-v $HOME:/home/user \
	-v $PWD:/data \
	-u $UID_GID \
	--entrypoint /bin/bash \
	${DOCKER_IMG} "$@"

else
    set -x
    docker run --rm -i ${DOCKER_TTY_ARGS} \
	-v $HOME:/home/user \
	-v $PWD:/data \
	-u $UID_GID \
	${DOCKER_IMG} "$@"
fi
